version: '3.7'

# docker-compose -f docker-compose-postgres.yml up
services:

  postdb:
    image: postgres
    container_name: my_postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: ps
      POSTGRES_PASSWORD: secret