server:
  port: 8080

##
#
spring:
  profiles:
    active: dev
  data:
    mongodb:
      database: webflux_security_demo
      host: localhost
      port: 27017
  thymeleaf:
    enabled: true
    suffix: .html
#      uri: mongodb://mongo:27017/webflux_security_demo
---
spring:
  profiles: prod
  data:
    mongodb:
      uri: mongodb://my-mongo:27017/webflux_security_demo
