server:
  port: 8080

##
#
spring:
  profiles:
    active: dev
  data:
    mongodb:
      database: webflux_security_demo
      host: my_mongodb
      port: 27017
#      uri: mongodb://mongo:27017/webflux_security_demo


