server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    driver-class-name: org.h2.Driver
    data-username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true

