GET http://localhost:8090/oauth2/token/refresh?refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJwc2tAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCJdLCJhdGkiOiJhZjAwNTM4MC00ZWEyLTQ4ZGItOWNjNi0xODk0NWUwOWY4ZTYiLCJleHAiOjE1OTA3MjY3MDYsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiI3YjJmMzJjYi1lODQ2LTQ4NzEtYjAwYS00Y2E3MTY2NmFkODYiLCJjbGllbnRfaWQiOiJ0ZXN0Q2xpZW50SWQifQ.LAtyg_3MKdGTMzRkPr8_ijnyUcEoA8Vde_FskI6enbE

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJwc2tAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCJdLCJhdGkiOiJhZjAwNTM4MC00ZWEyLTQ4ZGItOWNjNi0xODk0NWUwOWY4ZTYiLCJleHAiOjE1OTA3MjY3MDYsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiI3YjJmMzJjYi1lODQ2LTQ4NzEtYjAwYS00Y2E3MTY2NmFkODYiLCJjbGllbnRfaWQiOiJ0ZXN0Q2xpZW50SWQifQ.LAtyg_3MKdGTMzRkPr8_ijnyUcEoA8Vde_FskI6enbE
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJwc2tAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCJdLCJhdGkiOiJjYzU2YzkzMy04MTg4LTQxYmYtYTNjOC1hODJmN2NlZTVjMWIiLCJleHAiOjE1OTA3MjY3MDYsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiI3YjJmMzJjYi1lODQ2LTQ4NzEtYjAwYS00Y2E3MTY2NmFkODYiLCJjbGllbnRfaWQiOiJ0ZXN0Q2xpZW50SWQifQ.9GQxHRms0YzIYgc4ywj5itx2s3i_AJ364Mso94BaqTo